import type { Metadata } from "next";
import "./globals.css";

import { Inter, Gloock } from "next/font/google";
import Footer from "@/app/_footer";
import TailwindIndicator from "@/app/_components/TailwindIndicator";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const gloock = Gloock({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gloock",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${gloock.variable} font-sans antialiased`}
      >
        {children}
        <Footer />
        {process.env.NODE_ENV === "development" && <TailwindIndicator />}
      </body>
    </html>
  );
}
